```{r}
library(readr)
library(caret)
library(GGally)
library(ggplot2)
library(dplyr)
```

```{r}
data = read_csv("D:/UNI/SEMESTER 6/Jaringan Syaraf Tiruan/LVQ/Breast_Cancer_Wisconsin.csv")
data = data[, -c(1, 13, 14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33)]
str(data)
```

```{r}
data$class = as.numeric(factor(data$diagnosis, levels = c("M", "B"), labels = c(1, 2)))
data = data[, -1]

x = c("radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean", "compactness_mean", "concavity_mean", "concave points_mean", "symmetry_mean", "fractal_dimension_mean")
fitur = data[, x]

process = preProcess(fitur, method = c("range"))
normalisasi = predict(process, fitur)
data = cbind(normalisasi, class = data$class)
```

```{r}
ggpairs(data,
        columns = c("radius_mean", "texture_mean", "smoothness_mean", "compactness_mean", "concavity_mean"),
        aes(color = as.factor(class)),
        upper = list(continuous = wrap("points")),
        diag = list(continuous = wrap("barDiag")),
        lower = list(continuous = wrap("points")),
        labels = c("Kelas 1", "Kelas 2"))
```

```{r}
set.seed(2025)
split_class = function(df) {
  index = sample(2, nrow(df), replace = TRUE, prob = c(0.8, 0.2))
  list(train = df[index == 1, ], test = df[index == 2, ])
}

class1 = subset(data, class == 1)
class2 = subset(data, class == 2)


train1 = split_class(class1)$train
test1 = split_class(class1)$test
train2 = split_class(class2)$train
test2 = split_class(class2)$test

xtrain = rbind(train1, train2)
xtest = rbind(test1, test2)
```

```{r}
set.seed(2025)
C1 = class1[sample(nrow(class1), 1), x]
C2 = class2[sample(nrow(class2), 1), x]
C = rbind(C1, C2)  # ini C awal
C_class = c(1, 2)
```

```{r}
# Training
train_lvq = function(xtrain, C, C_class, alpha_t, beta, MaxEpoch, x) {
  C_t = C  # bobot awal (C)
  Epoch = 0
  Eps = 1e-9  # minimum error 
  
  while ((Epoch < MaxEpoch) && (alpha_t > Eps)) {
    for (i in 1:nrow(xtrain)) {
      x_i = as.numeric(xtrain[i, x])  # input vector xᵢ

      # hitung jarak Euclidean
      d_ij = apply(C_t, 1, function(C_j) sqrt(sum((x_i - C_j)^2)))
      j_min = which.min(d_ij)  #bobot terdekat

      if (C_class[j_min] == xtrain$class[i]) {
        # jika kelas cocok: update ke arah x_i
        C_t[j_min, ] = C_t[j_min, ] + alpha_t * (x_i - C_t[j_min, ])
      } else {
        # jika kelas tidak cocok: update menjauhi x_i
        C_t[j_min, ] = C_t[j_min, ] - alpha_t * (x_i - C_t[j_min, ])
      }
    }

    # pengurangan learning rate
    alpha_t = alpha_t * beta
    Epoch = Epoch + 1
  }
  return(C_t)
}
```

```{r}
predict_lvq = function(xdata, C, C_class, x) {
  predicted_class = vector(length = nrow(xdata))
  
  for (i in 1:nrow(xdata)) {
    x_i = as.numeric(xdata[i, x])  # input vektor xᵢ
    
    # hitung jarak euclidean ke semua bobot C_j
    d_ij = apply(C, 1, function(C_j) sqrt(sum((x_i - C_j)^2)))
    
    j_min = which.min(d_ij)  # cari bobot terdekat
    predicted_class[i] = C_class[j_min]
  }
  
  return(predicted_class)
}
```


```{r}
evaluate_lvq = function(xdata, predicted_class) {
  actual_class = xdata$class
  accuracy = sum(actual_class == predicted_class) / length(actual_class)
  return(accuracy)
}
```

```{r}
training = data.frame(alpha_0 = numeric(),
                      beta = numeric(),
                      MaxEpoch = numeric(),
                      accuracy = numeric())

for (alpha_0 in c(0.005, 0.01, 0.05, 0.1, 0.2)) {
  for (beta in c(0.01, 0.05, 0.1, 0.3, 0.5, 0.8)) {
    for (MaxEpoch in c(50)) {
      C_trained = train_lvq(xtrain, C, C_class, alpha_t = alpha_0, beta = beta, MaxEpoch = MaxEpoch, x = x)
      pred_class = predict_lvq(xtrain, C_trained, C_class, x)
      acc = evaluate_lvq(xtrain, pred_class)

      training = rbind(training, data.frame(alpha_0 = alpha_0, beta = beta, MaxEpoch = MaxEpoch, accuracy = round(acc, 5)))
    }
  }
}

print(training)
```

```{r}
testing = data.frame(alpha_0 = numeric(),
                      beta = numeric(),
                      MaxEpoch = numeric(),
                      accuracy = numeric())

for (alpha_0 in c(0.005)) {
  for (beta in c(0.5)) {
    for (MaxEpoch in c(50)) {
      C_trained = train_lvq(xtrain, C, C_class, alpha_t = alpha_0, beta = beta, MaxEpoch = MaxEpoch, x = x)
      pred_class = predict_lvq(xtest, C_trained, C_class, x)
      acc = evaluate_lvq(xtest, pred_class)

      testing = rbind(testing, data.frame(alpha_0 = alpha_0, beta = beta, MaxEpoch = MaxEpoch, accuracy = round(acc, 5)))
    }
  }
}

print(testing)
```

```{r}
# Ubah ke faktor
actual = as.factor(xtest$class)
predicted = as.factor(pred_class)

# Confusion matrix
conf_mat = confusionMatrix(predicted, actual)
print(conf_mat)

```
```{r}
# actual vs predicted
comparison = data.frame(
  Actual = xtest$class,
  Predicted = pred_class
)

pred = as.data.frame(pred_class)
dats = cbind(xtest, pred)
```

```{r}
# pca
pca_result = prcomp(xtest[, -11], scale. = TRUE)

# data frame pca
pca_data = as.data.frame(pca_result$x[, 1:2])
pca_data$Actual = as.factor(xtest$class)
pca_data$Predicted = as.factor(pred_class)

# plot
ggplot(pca_data, aes(x = PC1, y = PC2, color = Predicted, shape = Actual)) +
  geom_point(size = 4, alpha = 0.5) +
  labs(title = "PCA: predicted vs actual",
       x = "PC1",
       y = "PC2",
       color = "Predicted Class",
       shape = "Actual Class") +
  scale_color_brewer(palette = "Set1") +
  theme_minimal(base_size = 13)
```
